name: CI

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Create Simulator
        id: simulator
        run: |
          DEVICE_TYPE=$(xcrun simctl list devicetypes -j \
            | jq -r '.devicetypes[] | select(.name | contains("iPhone")) | .identifier' \
            | head -n 1)

          RUNTIME=$(xcrun simctl list runtimes -j \
            | jq -r '.runtimes[] | select(.name | contains("iOS") and .isAvailable == true) | .identifier' \
            | head -n 1)

          echo "Using device type: $DEVICE_TYPE"
          echo "Using runtime: $RUNTIME"

          DEVICE_ID=$(xcrun simctl create "CI-iPhone" "$DEVICE_TYPE" "$RUNTIME")

          echo "device_id=$DEVICE_ID" >> $GITHUB_OUTPUT


      - name: Boot Simulator
        run: |
          xcrun simctl boot CI-iPhone || true

      - name: Build and Test with Coverage
        run: |
          set -o pipefail
          xcodebuild \
            -project LaterApp/LaterApp.xcodeproj \
            -scheme LaterApp \
            -destination "platform=iOS Simulator,name=CI-iPhone" \
            -enableCodeCoverage YES \
            clean test

      - name: Delete Simulator
        if: always()
        run: |
          xcrun simctl delete CI-iPhone
